/**
 * WorkIndex — Service Category & Questionnaire Configuration
 * ============================================================
 * AUTO-GENERATED by WorkIndex Admin CMS.
 * DO NOT edit manually — use the admin panel to modify.
 * Generated: 2026-04-02T14:38:20.897Z
 */
 
const WI_SERVICES = {
 
  // ─── Master list of all service categories ──────────────
  list: [
    {
        "value": "itr",
        "label": "ITR Filing",
        "icon": "📄",
        "color": "#8b5cf6"
    },
    {
        "value": "gst",
        "label": "GST Services",
        "icon": "🧾",
        "color": "#3b82f6"
    },
    {
        "value": "accounting",
        "label": "Accounting",
        "icon": "📊",
        "color": "#10b981"
    },
    {
        "value": "audit",
        "label": "Audit",
        "icon": "🔍",
        "color": "#f59e0b"
    },
    {
        "value": "photography",
        "label": "Photography",
        "icon": "📷",
        "color": "#ec4899"
    },
    {
        "value": "development",
        "label": "Development",
        "icon": "💻",
        "color": "#06b6d4"
    }
],
 
  // ─── Quick lookup maps (auto-generated from list) ───────
  get labels() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.label);
    return m;
  },
  get colors() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.color);
    return m;
  },
  get icons() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.icon);
    return m;
  },
 
  // ─── Landing page search aliases ────────────────────────
  searchAliases: {
    "itr filing": "itr",
    "income tax": "itr",
    "tax": "itr",
    "itr": "itr",
    "gst": "gst",
    "gst services": "gst",
    "accounting": "accounting",
    "bookkeeping": "accounting",
    "audit": "audit",
    "statutory audit": "audit",
    "photography": "photography",
    "photo": "photography",
    "photographer": "photography",
    "development": "development",
    "dev": "development",
    "web": "development",
    "website": "development",
    "app": "development"
},
 
  // ─── Credit cost per service ─────────────────────────────
  creditCost: {
    "itr": 20,
    "gst": 20,
    "accounting": 20,
    "audit": 20,
    "photography": 10,
    "development": 15
},
 
  // ─── Max approaches per request ──────────────────────────
  maxApproaches: {
    "itr": 5,
    "gst": 5,
    "accounting": 5,
    "audit": 5,
    "photography": 5,
    "development": 5
},
 
  // ─── Questionnaire (nested structure) ────────────────────
  questionnaire: {
 
    serviceSelection: {
      id: 'service', key: 'service',
      type: 'service-picker',
      title: 'What service do you need?',
      subtitle: 'Select the category that best matches your requirement',
      required: true,
      useServiceList: true,
    },
 
    byService: {
      "itr": [
            {
                  "id": "itrTaxpayerType",
                  "key": "itrTaxpayerType",
                  "type": "single",
                  "title": "What is your taxpayer type?",
                  "required": true,
                  "options": [
                        {
                              "value": "salaried",
                              "label": "💼 Salaried Employee"
                        },
                        {
                              "value": "business",
                              "label": "🏢 Business Owner / Self-Employed"
                        },
                        {
                              "value": "freelancer",
                              "label": "💻 Freelancer / Consultant"
                        },
                        {
                              "value": "nri",
                              "label": "🌍 NRI (Non-Resident Indian)"
                        }
                  ]
            },
            {
                  "id": "itrAnnualIncome",
                  "key": "itrAnnualIncome",
                  "type": "single",
                  "title": "What is your approximate annual income?",
                  "required": true,
                  "options": [
                        {
                              "value": "below5L",
                              "label": "Below ₹5 Lakhs"
                        },
                        {
                              "value": "5L-10L",
                              "label": "₹5 – ₹10 Lakhs"
                        },
                        {
                              "value": "10L-20L",
                              "label": "₹10 – ₹20 Lakhs"
                        },
                        {
                              "value": "20L-50L",
                              "label": "₹20 – ₹50 Lakhs"
                        },
                        {
                              "value": "above50L",
                              "label": "Above ₹50 Lakhs"
                        }
                  ]
            },
            {
                  "id": "itrUrgency",
                  "key": "itrUrgency",
                  "type": "single",
                  "title": "When do you need it filed?",
                  "required": true,
                  "alias": "urgency",
                  "options": [
                        {
                              "value": "immediate",
                              "label": "🔴 Immediately (within 24 hours)"
                        },
                        {
                              "value": "2-3days",
                              "label": "🟠 Within 2–3 days"
                        },
                        {
                              "value": "week",
                              "label": "🟡 Within a week"
                        },
                        {
                              "value": "flexible",
                              "label": "🔵 Flexible / Before deadline"
                        }
                  ]
            }
      ],
      "gst": [
            {
                  "id": "gstServiceType",
                  "key": "gstServiceType",
                  "type": "single",
                  "title": "What GST service do you need?",
                  "required": true,
                  "options": [
                        {
                              "value": "new_registration",
                              "label": "📋 New GST Registration"
                        },
                        {
                              "value": "monthly_filing",
                              "label": "📊 Monthly GSTR Filing"
                        },
                        {
                              "value": "annual_return",
                              "label": "📁 Annual GST Return (GSTR-9)"
                        },
                        {
                              "value": "notice_handling",
                              "label": "⚠️ GST Notice / Scrutiny"
                        },
                        {
                              "value": "itc_reconciliation",
                              "label": "🔁 ITC Reconciliation"
                        }
                  ]
            },
            {
                  "id": "gstTurnover",
                  "key": "gstTurnover",
                  "type": "single",
                  "title": "What is your monthly business turnover?",
                  "required": true,
                  "options": [
                        {
                              "value": "below5L",
                              "label": "Below ₹5 Lakhs"
                        },
                        {
                              "value": "5L-20L",
                              "label": "₹5 – ₹20 Lakhs"
                        },
                        {
                              "value": "20L-50L",
                              "label": "₹20 – ₹50 Lakhs"
                        },
                        {
                              "value": "above50L",
                              "label": "Above ₹50 Lakhs"
                        }
                  ]
            },
            {
                  "id": "gstUrgency",
                  "key": "gstUrgency",
                  "type": "single",
                  "title": "When do you need this?",
                  "required": true,
                  "alias": "urgency",
                  "options": [
                        {
                              "value": "immediate",
                              "label": "🔴 Immediately"
                        },
                        {
                              "value": "2-3days",
                              "label": "🟠 Within 2–3 days"
                        },
                        {
                              "value": "week",
                              "label": "🟡 This week"
                        },
                        {
                              "value": "flexible",
                              "label": "🔵 Flexible"
                        }
                  ]
            }
      ],
      "accounting": [
            {
                  "id": "accountingServiceType",
                  "key": "accountingServiceType",
                  "type": "single",
                  "title": "What accounting service do you need?",
                  "required": true,
                  "options": [
                        {
                              "value": "bookkeeping",
                              "label": "📚 Monthly Bookkeeping"
                        },
                        {
                              "value": "payroll",
                              "label": "👥 Payroll Processing"
                        },
                        {
                              "value": "annual_accounts",
                              "label": "📋 Annual Accounts Preparation"
                        },
                        {
                              "value": "tds_filing",
                              "label": "📄 TDS Filing"
                        }
                  ]
            },
            {
                  "id": "accountingFrequency",
                  "key": "accountingFrequency",
                  "type": "single",
                  "title": "How often do you need accounting support?",
                  "required": true,
                  "options": [
                        {
                              "value": "monthly",
                              "label": "📅 Monthly (ongoing)"
                        },
                        {
                              "value": "quarterly",
                              "label": "🗓️ Quarterly"
                        },
                        {
                              "value": "annual",
                              "label": "📆 One-time / Annual"
                        }
                  ]
            },
            {
                  "id": "accountingTransactions",
                  "key": "accountingTransactions",
                  "type": "single",
                  "title": "How many transactions per month approximately?",
                  "required": true,
                  "options": [
                        {
                              "value": "below50",
                              "label": "Below 50"
                        },
                        {
                              "value": "50-200",
                              "label": "50 – 200"
                        },
                        {
                              "value": "200-500",
                              "label": "200 – 500"
                        },
                        {
                              "value": "above500",
                              "label": "Above 500"
                        }
                  ]
            }
      ],
      "audit": [
            {
                  "id": "auditType",
                  "key": "auditType",
                  "type": "single",
                  "title": "What type of audit do you need?",
                  "required": true,
                  "options": [
                        {
                              "value": "statutory_audit",
                              "label": "📋 Statutory Audit"
                        },
                        {
                              "value": "tax_audit",
                              "label": "📄 Tax Audit (Section 44AB)"
                        },
                        {
                              "value": "internal_audit",
                              "label": "🔍 Internal Audit"
                        },
                        {
                              "value": "gst_audit",
                              "label": "🧾 GST Audit"
                        }
                  ]
            },
            {
                  "id": "auditTurnover",
                  "key": "auditTurnover",
                  "type": "single",
                  "title": "What is your annual business turnover?",
                  "required": true,
                  "options": [
                        {
                              "value": "below1Cr",
                              "label": "Below ₹1 Crore"
                        },
                        {
                              "value": "1Cr-5Cr",
                              "label": "₹1 – ₹5 Crore"
                        },
                        {
                              "value": "5Cr-20Cr",
                              "label": "₹5 – ₹20 Crore"
                        },
                        {
                              "value": "above20Cr",
                              "label": "Above ₹20 Crore"
                        }
                  ]
            }
      ],
      "photography": [
            {
                  "id": "photographyType",
                  "key": "photographyType",
                  "type": "single",
                  "title": "What type of photography do you need?",
                  "required": true,
                  "options": [
                        {
                              "value": "wedding",
                              "label": "💍 Wedding Photography"
                        },
                        {
                              "value": "portrait",
                              "label": "🤳 Portrait / Headshots"
                        },
                        {
                              "value": "product",
                              "label": "📦 Product / E-Commerce"
                        },
                        {
                              "value": "corporate",
                              "label": "🏢 Corporate / Event"
                        },
                        {
                              "value": "real_estate",
                              "label": "🏠 Real Estate / Architecture"
                        }
                  ]
            },
            {
                  "id": "photographyDuration",
                  "key": "photographyDuration",
                  "type": "single",
                  "title": "How long is the shoot?",
                  "required": true,
                  "alias": "urgency",
                  "options": [
                        {
                              "value": "1-2hours",
                              "label": "1–2 hours"
                        },
                        {
                              "value": "half-day",
                              "label": "Half day (3–5 hours)"
                        },
                        {
                              "value": "full-day",
                              "label": "Full day"
                        },
                        {
                              "value": "multi-day",
                              "label": "Multiple days"
                        }
                  ]
            }
      ],
      "development": [
            {
                  "id": "devProjectType",
                  "key": "devProjectType",
                  "type": "single",
                  "title": "What type of project do you need?",
                  "required": true,
                  "options": [
                        {
                              "value": "website",
                              "label": "🌐 Website (informational)"
                        },
                        {
                              "value": "ecommerce",
                              "label": "🛒 E-Commerce Store"
                        },
                        {
                              "value": "webapp",
                              "label": "💻 Web Application / SaaS"
                        },
                        {
                              "value": "mobile-app",
                              "label": "📱 Mobile App (Android / iOS)"
                        },
                        {
                              "value": "api",
                              "label": "🔌 API / Backend Development"
                        },
                        {
                              "value": "redesign",
                              "label": "🎨 Website Redesign / Revamp"
                        },
                        {
                              "value": "maintenance",
                              "label": "🔧 Maintenance / Bug Fix"
                        }
                  ]
            },
            {
                  "id": "devTimeline",
                  "key": "devTimeline",
                  "type": "single",
                  "title": "What is your project timeline?",
                  "required": true,
                  "alias": "urgency",
                  "options": [
                        {
                              "value": "immediate",
                              "label": "🔴 ASAP (within 1 week)"
                        },
                        {
                              "value": "2-3days",
                              "label": "🟠 Within 2–4 weeks"
                        },
                        {
                              "value": "month",
                              "label": "🟡 1–3 months"
                        },
                        {
                              "value": "flexible",
                              "label": "🔵 Flexible"
                        }
                  ]
            }
      ]
},
 
    common: {
      serviceLocationType: {
        id: 'service_location_type', key: 'serviceLocationType',
        type: 'single', required: true,
        title: 'Where do you need the service?',
        options: [
          { value: 'online',              label: 'Online / Remotely',        icon: '💻' },
          { value: 'my-location',         label: 'At my location',           icon: '🏠' },
          { value: 'professional-office', label: "At professional's office", icon: '🏢' },
        ],
      },
      fullAddress: {
        id: 'full_address', key: 'fullAddress',
        type: 'address', required: true,
        title: 'Enter your address',
        fields: [
          { key: 'building', label: 'Flat / Building / House No.', placeholder: 'e.g. 4B, Sunrise Apartments', required: true },
          { key: 'area',     label: 'Area / Street / Locality',    placeholder: 'e.g. Koramangala 5th Block',  required: true },
          { key: 'pincode',  label: 'Pincode',                     placeholder: 'e.g. 560095',                required: true, type: 'pincode' },
          { key: 'city',     label: 'City',                        placeholder: 'e.g. Bengaluru',             required: true },
          { key: 'state',    label: 'State',                       placeholder: 'e.g. Karnataka',             required: true },
          { key: 'landmark', label: 'Landmark (optional)',         placeholder: 'e.g. Near Indiranagar metro', required: false },
        ],
      },
      clientLocation: {
        id: 'client_location', key: 'clientLocation',
        type: 'address-simple', required: true,
        title: 'Where are you based?',
        fields: [
          { key: 'pincode', label: 'Pincode', placeholder: 'e.g. 560095', required: true, type: 'pincode' },
          { key: 'city',    label: 'City',    placeholder: 'e.g. Bengaluru', required: true },
          { key: 'state',   label: 'State',   placeholder: 'e.g. Karnataka', required: true },
        ],
      },
      urgency: {
        id: 'urgency', key: 'urgency',
        type: 'single', required: true,
        title: 'When do you need this done?',
        options: [
          { value: 'immediate', label: 'Immediately (within 24 hours)', icon: '🔴' },
          { value: '2-3days',   label: 'Within 2–3 days',               icon: '🟠' },
          { value: 'week',      label: 'Within a week',                  icon: '🟡' },
          { value: 'month',     label: 'Within a month',                 icon: '🟢' },
          { value: 'flexible',  label: 'Flexible / No rush',             icon: '🔵' },
        ],
      },
      budget: {
        id: 'budget', key: 'budget',
        type: 'budget', required: false,
        title: 'What is your budget?',
        min: 100, max: 500000, step: 100, currency: '₹',
        placeholder: 'Enter your budget in ₹',
      },
      description: {
        id: 'description', key: 'description',
        type: 'textarea', required: true,
        title: 'Describe your requirement',
        placeholder: 'Please describe what you need in detail...',
        minLength: 20,
      },
      preferredProfessional: {
        id: 'preferred_professional', key: 'preferredProfessional',
        type: 'single', required: false,
        title: 'What type of professional do you prefer?',
        options: [
          { value: 'individual_ca', label: 'Individual CA / Freelancer', icon: '👤' },
          { value: 'firm',          label: 'CA Firm / Agency',           icon: '🏢' },
          { value: 'no_preference', label: 'No preference',              icon: '🤷' },
        ],
      },
      contactMethod: {
        id: 'contact_method', key: 'contactMethod',
        type: 'single', required: true,
        title: 'How should professionals contact you?',
        options: [
          { value: 'platform_chat', label: 'Chat on WorkIndex',     icon: '💬' },
          { value: 'phone',         label: 'Phone call / WhatsApp', icon: '📞' },
          { value: 'email',         label: 'Email',                  icon: '✉️' },
          { value: 'any',           label: 'Any method is fine',     icon: '✅' },
        ],
      },
    },
 
    expert: [
      {
        id: 'expert_services', key: 'servicesOffered',
        type: 'multi', required: true,
        title: 'What services do you offer?',
        useServiceList: true,
      },
      {
        id: 'expert_specialization', key: 'specialization',
        type: 'single', required: true,
        title: 'What is your primary specialization?',
        options: [
          { value: 'Chartered Accountant', label: 'Chartered Accountant (CA)', icon: '🎓' },
          { value: 'Cost Accountant',       label: 'Cost Accountant (CMA)',     icon: '🎓' },
          { value: 'Tax Consultant',        label: 'Tax Consultant',            icon: '📄' },
          { value: 'GST Consultant',        label: 'GST Consultant',            icon: '🧾' },
          { value: 'Bookkeeper',            label: 'Bookkeeper / Accountant',   icon: '📊' },
          { value: 'Photographer',          label: 'Photographer',              icon: '📷' },
          { value: 'Web Developer',         label: 'Web / App Developer',       icon: '💻' },
          { value: 'Other',                 label: 'Other Professional',         icon: '🔧' },
        ],
      },
      {
        id: 'expert_experience', key: 'yearsOfExperience',
        type: 'single', required: true,
        title: 'How many years of experience do you have?',
        options: [
          { value: '0-1',  label: 'Less than 1 year',   icon: '🌱' },
          { value: '1-3',  label: '1 – 3 years',        icon: '📈' },
          { value: '3-5',  label: '3 – 5 years',        icon: '📈' },
          { value: '5-10', label: '5 – 10 years',       icon: '⭐' },
          { value: '10+',  label: 'More than 10 years', icon: '🏆' },
        ],
      },
      {
        id: 'expert_location', key: 'serviceLocationType',
        type: 'single', required: true,
        title: 'Where do you prefer to work?',
        options: [
          { value: 'online', label: 'Online / Remotely only',      icon: '💻' },
          { value: 'local',  label: 'Local (in-person preferred)', icon: '📍' },
          { value: 'both',   label: 'Both online and in-person',  icon: '🌐' },
        ],
      },
      {
        id: 'expert_city', key: 'city',
        type: 'single', required: true,
        title: 'Which city are you based in?',
        options: [], isTextInput: true, placeholder: 'Enter your city',
      },
      {
        id: 'expert_state', key: 'state',
        type: 'single', required: true,
        title: 'Which state are you in?',
        options: [
          { value: 'Karnataka',      label: 'Karnataka' },
          { value: 'Maharashtra',    label: 'Maharashtra' },
          { value: 'Tamil Nadu',     label: 'Tamil Nadu' },
          { value: 'Delhi',          label: 'Delhi' },
          { value: 'Telangana',      label: 'Telangana' },
          { value: 'Gujarat',        label: 'Gujarat' },
          { value: 'Rajasthan',      label: 'Rajasthan' },
          { value: 'West Bengal',    label: 'West Bengal' },
          { value: 'Uttar Pradesh',  label: 'Uttar Pradesh' },
          { value: 'Kerala',         label: 'Kerala' },
          { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
          { value: 'Punjab',         label: 'Punjab' },
          { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
          { value: 'Bihar',          label: 'Bihar' },
          { value: 'Other',          label: 'Other' },
        ],
      },
      {
        id: 'expert_pincode', key: 'pincode',
        type: 'single', required: true,
        title: 'What is your pincode?',
        options: [], isTextInput: true, placeholder: 'Enter 6-digit pincode',
      },
      {
        id: 'expert_bio', key: 'bio',
        type: 'textarea', required: true,
        title: 'Tell clients about yourself',
        placeholder: 'e.g. I am a CA with 8 years of experience...',
        minLength: 50,
      },
    ],
 
  },
 
  // ─── Answer tag formatters (for browse cards) ────────────
  answerTagFormatters: {
    itrTaxpayerType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    itrAnnualIncome: function(v){ return v.replace('above','> ').replace('below','< '); },
    gstServiceType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    gstTurnover: function(v){ return v.replace('above','> ').replace('below','< '); },
    accountingServiceType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    accountingFrequency: function(v){ return v.replace(/-/g,' '); },
    accountingTransactions: function(v){ return v + ' txns/mo'; },
    auditType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    auditTurnover: function(v){ return v.replace('above','> ').replace('below','< '); },
    photographyType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    photographyDuration: function(v){ return v.replace(/-/g,' '); },
    devProjectType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    devTimeline: function(v){ return v.replace(/-/g,' '); }
  },
 
};
 
Object.freeze(WI_SERVICES);
