/**
 * WorkIndex — Service Category & Questionnaire Configuration
 * ============================================================
 * AUTO-GENERATED by WorkIndex Admin CMS.
 * DO NOT edit manually — use the admin panel to modify.
 * Generated: 2026-04-15T14:36:13.550Z
 */
 
const WI_SERVICES = {
 
  // ─── Master list of all service categories ──────────────
  list: [
    {
        "value": "itr",
        "label": "ITR Filing",
        "icon": "📄",
        "color": "#8b5cf6"
    },
    {
        "value": "gst",
        "label": "GST Services",
        "icon": "🧾",
        "color": "#3b82f6"
    },
    {
        "value": "accounting",
        "label": "Accounting",
        "icon": "📊",
        "color": "#10b981"
    },
    {
        "value": "audit",
        "label": "Audit",
        "icon": "🔍",
        "color": "#f59e0b"
    },
    {
        "value": "photography",
        "label": "Photography",
        "icon": "📷",
        "color": "#ec4899"
    },
    {
        "value": "development",
        "label": "Development",
        "icon": "💻",
        "color": "#06b6d4"
    }
],
 
  // ─── Quick lookup maps (auto-generated from list) ───────
  get labels() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.label);
    return m;
  },
  get colors() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.color);
    return m;
  },
  get icons() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.icon);
    return m;
  },
 
  // ─── Landing page search aliases ────────────────────────
  searchAliases: {
    "itr filing": "itr",
    "income tax": "itr",
    "tax": "itr",
    "itr": "itr",
    "gst": "gst",
    "gst services": "gst",
    "accounting": "accounting",
    "bookkeeping": "accounting",
    "audit": "audit",
    "statutory audit": "audit",
    "photography": "photography",
    "photo": "photography",
    "photographer": "photography",
    "development": "development",
    "dev": "development",
    "web": "development",
    "website": "development",
    "app": "development"
},
 
  // ─── Credit cost per service ─────────────────────────────
  creditCost: {
    "itr": 20,
    "gst": 20,
    "accounting": 20,
    "audit": 20,
    "photography": 10,
    "development": 15
},
 
  // ─── Max approaches per request ──────────────────────────
  maxApproaches: {
    "itr": 5,
    "gst": 5,
    "accounting": 5,
    "audit": 5,
    "photography": 5,
    "development": 5
},
 
  // ─── Questionnaire (nested structure) ────────────────────
  questionnaire: {
 
    serviceSelection: {
      id: 'service', key: 'service',
      type: 'service-picker',
      title: 'What service do you need?',
      subtitle: 'Select the category that best matches your requirement',
      required: true,
      useServiceList: true,
    },
 
    byService: {
      "itr": [
            {
                  "id": "itrTaxpayerType",
                  "key": "itrTaxpayerType",
                  "type": "single",
                  "required": true,
                  "title": "What is your taxpayer type?",
                  "options": [
                        {
                              "value": "salaried",
                              "label": "💼 Salaried Employee"
                        },
                        {
                              "value": "business",
                              "label": "🏢 Business Owner / Self-Employed"
                        },
                        {
                              "value": "freelancer",
                              "label": "💻 Freelancer / Consultant"
                        },
                        {
                              "value": "nri",
                              "label": "🌍 NRI (Non-Resident Indian)"
                        }
                  ]
            },
            {
                  "id": "itrAnnualIncome",
                  "key": "itrAnnualIncome",
                  "type": "single",
                  "required": true,
                  "title": "What is your approximate annual income?",
                  "options": [
                        {
                              "value": "below5L",
                              "label": "Below ₹5 Lakhs"
                        },
                        {
                              "value": "5L-10L",
                              "label": "₹5 – ₹10 Lakhs"
                        },
                        {
                              "value": "10L-20L",
                              "label": "₹10 – ₹20 Lakhs"
                        },
                        {
                              "value": "20L-50L",
                              "label": "₹20 – ₹50 Lakhs"
                        },
                        {
                              "value": "above50L",
                              "label": "Above ₹50 Lakhs"
                        }
                  ]
            },
            {
                  "id": "itrIncomeSources",
                  "key": "itrIncomeSources",
                  "type": "multi",
                  "required": true,
                  "title": "Sources of income",
                  "subtitle": "Select all that apply",
                  "options": [
                        {
                              "value": "salary",
                              "label": "Salary"
                        },
                        {
                              "value": "business",
                              "label": "Business income"
                        },
                        {
                              "value": "rental",
                              "label": "Rental income"
                        },
                        {
                              "value": "capital",
                              "label": "Capital gains"
                        },
                        {
                              "value": "foreign",
                              "label": "Foreign income"
                        },
                        {
                              "value": "interest",
                              "label": "Interest income"
                        },
                        {
                              "value": "other",
                              "label": "Other"
                        }
                  ]
            },
            {
                  "id": "itrFilingType",
                  "key": "itrFilingType",
                  "type": "single",
                  "required": true,
                  "title": "Filing requirement",
                  "subtitle": "What type of return do you need?",
                  "options": [
                        {
                              "value": "current",
                              "label": "Current year return"
                        },
                        {
                              "value": "previous",
                              "label": "Previous year return"
                        },
                        {
                              "value": "revised",
                              "label": "Revised return"
                        },
                        {
                              "value": "notice",
                              "label": "Tax notice handling"
                        }
                  ]
            },
            {
                  "id": "itrTaxPlanning",
                  "key": "itrTaxPlanning",
                  "type": "single",
                  "required": true,
                  "title": "Need tax planning advice?",
                  "options": [
                        {
                              "value": "yes",
                              "label": "✅ Yes, I need tax planning advice"
                        },
                        {
                              "value": "no",
                              "label": "❌ No, just file my return"
                        }
                  ]
            }
      ],
      "gst": [
            {
                  "id": "gstServiceType",
                  "key": "gstServiceType",
                  "type": "single",
                  "required": true,
                  "title": "What GST service do you need?",
                  "options": [
                        {
                              "value": "new_registration",
                              "label": "📋 New GST Registration"
                        },
                        {
                              "value": "monthly_filing",
                              "label": "📊 Monthly GSTR Filing"
                        },
                        {
                              "value": "annual_return",
                              "label": "📁 Annual GST Return (GSTR-9)"
                        },
                        {
                              "value": "notice_handling",
                              "label": "⚠️ GST Notice / Scrutiny"
                        },
                        {
                              "value": "itc_reconciliation",
                              "label": "🔁 ITC Reconciliation"
                        }
                  ]
            },
            {
                  "id": "gstBusinessType",
                  "key": "gstBusinessType",
                  "type": "single",
                  "required": true,
                  "title": "Business type",
                  "subtitle": "Select your business structure",
                  "options": [
                        {
                              "value": "proprietorship",
                              "label": "Proprietorship"
                        },
                        {
                              "value": "partnership",
                              "label": "Partnership"
                        },
                        {
                              "value": "llp",
                              "label": "LLP"
                        },
                        {
                              "value": "pvt_ltd",
                              "label": "Private Limited Company"
                        },
                        {
                              "value": "opc",
                              "label": "OPC (One Person Company)"
                        },
                        {
                              "value": "other",
                              "label": "Other"
                        }
                  ]
            },
            {
                  "id": "gstTurnover",
                  "key": "gstTurnover",
                  "type": "single",
                  "required": true,
                  "title": "What is your monthly business turnover?",
                  "options": [
                        {
                              "value": "below5L",
                              "label": "Below ₹5 Lakhs"
                        },
                        {
                              "value": "5L-20L",
                              "label": "₹5 – ₹20 Lakhs"
                        },
                        {
                              "value": "20L-50L",
                              "label": "₹20 – ₹50 Lakhs"
                        },
                        {
                              "value": "above50L",
                              "label": "Above ₹50 Lakhs"
                        }
                  ]
            },
            {
                  "id": "gstExisting",
                  "key": "gstExisting",
                  "type": "single",
                  "required": true,
                  "title": "Do you already have a GSTIN?",
                  "options": [
                        {
                              "value": "yes",
                              "label": "✅ Yes, I have GSTIN"
                        },
                        {
                              "value": "no",
                              "label": "❌ No, need new registration"
                        }
                  ]
            }
      ],
      "accounting": [
            {
                  "id": "accountingBusinessType",
                  "key": "accountingBusinessType",
                  "type": "single",
                  "required": true,
                  "title": "Business type",
                  "subtitle": "Select your business structure",
                  "options": [
                        {
                              "value": "proprietorship",
                              "label": "Proprietorship"
                        },
                        {
                              "value": "partnership",
                              "label": "Partnership"
                        },
                        {
                              "value": "llp",
                              "label": "LLP"
                        },
                        {
                              "value": "pvt_ltd",
                              "label": "Private Limited Company"
                        },
                        {
                              "value": "opc",
                              "label": "OPC"
                        },
                        {
                              "value": "other",
                              "label": "Other"
                        }
                  ]
            },
            {
                  "id": "accountingServiceType",
                  "key": "accountingServiceType",
                  "type": "single",
                  "required": true,
                  "title": "What accounting service do you need?",
                  "options": [
                        {
                              "value": "bookkeeping",
                              "label": "📚 Monthly Bookkeeping"
                        },
                        {
                              "value": "payroll",
                              "label": "👥 Payroll Processing"
                        },
                        {
                              "value": "annual_accounts",
                              "label": "📋 Annual Accounts Preparation"
                        },
                        {
                              "value": "tds_filing",
                              "label": "📄 TDS Filing"
                        }
                  ]
            },
            {
                  "id": "accountingFrequency",
                  "key": "accountingFrequency",
                  "type": "single",
                  "required": true,
                  "title": "How often do you need accounting support?",
                  "options": [
                        {
                              "value": "monthly",
                              "label": "📅 Monthly (ongoing)"
                        },
                        {
                              "value": "quarterly",
                              "label": "🗓️ Quarterly"
                        },
                        {
                              "value": "annual",
                              "label": "📆 One-time / Annual"
                        }
                  ]
            },
            {
                  "id": "accountingSoftware",
                  "key": "accountingSoftware",
                  "type": "single",
                  "required": true,
                  "title": "Accounting software used",
                  "subtitle": "Which software do you currently use?",
                  "options": [
                        {
                              "value": "tally",
                              "label": "Tally"
                        },
                        {
                              "value": "zoho",
                              "label": "Zoho Books"
                        },
                        {
                              "value": "quickbooks",
                              "label": "QuickBooks"
                        },
                        {
                              "value": "busy",
                              "label": "Busy"
                        },
                        {
                              "value": "none",
                              "label": "None / Manual"
                        },
                        {
                              "value": "other",
                              "label": "Other"
                        }
                  ]
            },
            {
                  "id": "accountingTransactions",
                  "key": "accountingTransactions",
                  "type": "single",
                  "required": true,
                  "title": "How many transactions per month approximately?",
                  "options": [
                        {
                              "value": "below50",
                              "label": "Below 50"
                        },
                        {
                              "value": "50-200",
                              "label": "50 – 200"
                        },
                        {
                              "value": "200-500",
                              "label": "200 – 500"
                        },
                        {
                              "value": "above500",
                              "label": "Above 500"
                        }
                  ]
            }
      ],
      "audit": [
            {
                  "id": "auditType",
                  "key": "auditType",
                  "type": "single",
                  "required": true,
                  "title": "What type of audit do you need?",
                  "options": [
                        {
                              "value": "statutory_audit",
                              "label": "📋 Statutory Audit"
                        },
                        {
                              "value": "tax_audit",
                              "label": "📄 Tax Audit (Section 44AB)"
                        },
                        {
                              "value": "internal_audit",
                              "label": "🔍 Internal Audit"
                        },
                        {
                              "value": "gst_audit",
                              "label": "🧾 GST Audit"
                        }
                  ]
            },
            {
                  "id": "auditOrgType",
                  "key": "auditOrgType",
                  "type": "single",
                  "required": true,
                  "title": "Organization type",
                  "subtitle": "Select your business structure",
                  "options": [
                        {
                              "value": "proprietorship",
                              "label": "Proprietorship"
                        },
                        {
                              "value": "partnership",
                              "label": "Partnership"
                        },
                        {
                              "value": "llp",
                              "label": "LLP"
                        },
                        {
                              "value": "pvt_ltd",
                              "label": "Private Limited Company"
                        },
                        {
                              "value": "public",
                              "label": "Public Limited Company"
                        },
                        {
                              "value": "other",
                              "label": "Other"
                        }
                  ]
            },
            {
                  "id": "auditTurnover",
                  "key": "auditTurnover",
                  "type": "single",
                  "required": true,
                  "title": "What is your annual business turnover?",
                  "options": [
                        {
                              "value": "below1Cr",
                              "label": "Below ₹1 Crore"
                        },
                        {
                              "value": "1Cr-5Cr",
                              "label": "₹1 – ₹5 Crore"
                        },
                        {
                              "value": "5Cr-20Cr",
                              "label": "₹5 – ₹20 Crore"
                        },
                        {
                              "value": "above20Cr",
                              "label": "Above ₹20 Crore"
                        }
                  ]
            },
            {
                  "id": "auditDeadline",
                  "key": "auditDeadline",
                  "type": "date",
                  "required": true,
                  "title": "Audit deadline",
                  "subtitle": "When do you need the audit completed?",
                  "placeholder": "e.g. March 31, 2026"
            }
      ],
      "photography": [
            {
                  "id": "photographyType",
                  "key": "photographyType",
                  "type": "single",
                  "required": true,
                  "title": "What type of photography do you need?",
                  "options": [
                        {
                              "value": "wedding",
                              "label": "💍 Wedding Photography"
                        },
                        {
                              "value": "portrait",
                              "label": "🤳 Portrait / Headshots"
                        },
                        {
                              "value": "product",
                              "label": "📦 Product / E-Commerce"
                        },
                        {
                              "value": "corporate",
                              "label": "🏢 Corporate / Event"
                        },
                        {
                              "value": "real_estate",
                              "label": "🏠 Real Estate / Architecture"
                        }
                  ]
            },
            {
                  "id": "photographyEventDate",
                  "key": "photographyEventDate",
                  "type": "date",
                  "required": true,
                  "title": "Event / shoot date",
                  "subtitle": "When is your event or photoshoot?",
                  "placeholder": "e.g. 15 May 2026"
            },
            {
                  "id": "photographyDuration",
                  "key": "photographyDuration",
                  "type": "single",
                  "required": true,
                  "title": "How long is the shoot?",
                  "options": [
                        {
                              "value": "few-hours",
                              "label": "Few hours"
                        },
                        {
                              "value": "half-day",
                              "label": "Half day (3–5 hours)"
                        },
                        {
                              "value": "full-day",
                              "label": "Full day"
                        },
                        {
                              "value": "multiple",
                              "label": "Multiple days"
                        }
                  ]
            },
            {
                  "id": "photographyVideography",
                  "key": "photographyVideography",
                  "type": "single",
                  "required": true,
                  "title": "Need videography also?",
                  "options": [
                        {
                              "value": "yes",
                              "label": "🎥 Yes, include videography"
                        },
                        {
                              "value": "no",
                              "label": "📷 No, photography only"
                        }
                  ]
            }
      ],
      "development": [
            {
                  "id": "devProjectType",
                  "key": "devProjectType",
                  "type": "single",
                  "required": true,
                  "title": "What type of project do you need?",
                  "options": [
                        {
                              "value": "website",
                              "label": "🌐 Website (informational)"
                        },
                        {
                              "value": "ecommerce",
                              "label": "🛒 E-Commerce Store"
                        },
                        {
                              "value": "webapp",
                              "label": "💻 Web Application / SaaS"
                        },
                        {
                              "value": "mobile-app",
                              "label": "📱 Mobile App (Android / iOS)"
                        },
                        {
                              "value": "api",
                              "label": "🔌 API / Backend Development"
                        },
                        {
                              "value": "redesign",
                              "label": "🎨 Website Redesign / Revamp"
                        },
                        {
                              "value": "maintenance",
                              "label": "🔧 Maintenance / Bug Fix"
                        }
                  ]
            },
            {
                  "id": "devProjectStage",
                  "key": "devProjectStage",
                  "type": "single",
                  "required": true,
                  "title": "Project stage",
                  "subtitle": "What stage is your project at?",
                  "options": [
                        {
                              "value": "idea",
                              "label": "Idea stage"
                        },
                        {
                              "value": "requirements",
                              "label": "Requirements defined"
                        },
                        {
                              "value": "design-ready",
                              "label": "Design ready"
                        },
                        {
                              "value": "partial",
                              "label": "Partially developed"
                        },
                        {
                              "value": "upgrade",
                              "label": "Existing system upgrade"
                        }
                  ]
            },
            {
                  "id": "devPlatform",
                  "key": "devPlatform",
                  "type": "multi",
                  "required": true,
                  "title": "Platform needed",
                  "subtitle": "Which platforms should it support?",
                  "options": [
                        {
                              "value": "android",
                              "label": "Android"
                        },
                        {
                              "value": "ios",
                              "label": "iOS"
                        },
                        {
                              "value": "web",
                              "label": "Web"
                        },
                        {
                              "value": "cross-platform",
                              "label": "Cross-platform"
                        },
                        {
                              "value": "not-sure",
                              "label": "Not sure yet"
                        }
                  ]
            },
            {
                  "id": "devTimeline",
                  "key": "devTimeline",
                  "type": "single",
                  "required": true,
                  "title": "What is your project timeline?",
                  "options": [
                        {
                              "value": "asap",
                              "label": "🔴 ASAP (within 1 week)"
                        },
                        {
                              "value": "1-2months",
                              "label": "🟠 1–2 months"
                        },
                        {
                              "value": "3-6months",
                              "label": "🟡 3–6 months"
                        },
                        {
                              "value": "flexible",
                              "label": "🔵 Flexible"
                        }
                  ]
            },
            {
                  "id": "devMaintenance",
                  "key": "devMaintenance",
                  "type": "single",
                  "required": true,
                  "title": "Need ongoing maintenance?",
                  "options": [
                        {
                              "value": "yes",
                              "label": "✅ Yes, need maintenance support"
                        },
                        {
                              "value": "no",
                              "label": "❌ No, just build and handover"
                        }
                  ]
            }
      ]
},
 
    common: {
    "service_location_type": {
        "id": "service_location_type",
        "key": "service_location_type",
        "type": "single",
        "required": true,
        "title": "Where do you need the service?",
        "subtitle": "Choose how you prefer to work with the professional",
        "options": [
            {
                "value": "online",
                "label": "Online / Remotely"
            },
            {
                "value": "my-location",
                "label": "At my location"
            },
            {
                "value": "professional-office",
                "label": "At professional's office"
            }
        ]
    },
    "full_address": {
        "id": "full_address",
        "key": "full_address",
        "type": "address",
        "required": true,
        "title": "Enter your address",
        "subtitle": "So we can find professionals near you",
        "fields": {
            "building": {
                "label": "Flat / Building / House No.",
                "placeholder": "e.g. 4B, Sunrise Apartments",
                "required": true
            },
            "area": {
                "label": "Area / Locality",
                "placeholder": "e.g. Koramangala 5th Block",
                "required": true
            },
            "pincode": {
                "label": "Pincode",
                "placeholder": "e.g. 560095",
                "required": true,
                "autoFillTrigger": true
            },
            "city": {
                "label": "City",
                "placeholder": "e.g. Bengaluru",
                "required": true,
                "autoFilled": true
            },
            "state": {
                "label": "State",
                "placeholder": "Select your state",
                "required": true,
                "type": "select",
                "autoFilled": true
            },
            "landmark": {
                "label": "Landmark (optional)",
                "placeholder": "e.g. Near Indiranagar metro",
                "required": false
            }
        }
    },
    "client_location": {
        "id": "client_location",
        "key": "clientLocation",
        "type": "address",
        "required": true,
        "title": "Where are you based?",
        "subtitle": "Helps match you with professionals in your region",
        "fields": {
            "pincode": {
                "label": "Pincode",
                "placeholder": "e.g. 560095",
                "required": true,
                "autoFillTrigger": true
            },
            "city": {
                "label": "City",
                "placeholder": "e.g. Bengaluru",
                "required": true,
                "autoFilled": true
            },
            "state": {
                "label": "State",
                "placeholder": "Select state",
                "required": true,
                "type": "select",
                "autoFilled": true
            }
        }
    },
    "urgency": {
        "id": "urgency",
        "key": "urgency",
        "type": "single",
        "required": true,
        "title": "When do you need this done?",
        "options": [
            {
                "value": "immediate",
                "label": "Immediately (within 24 hours)"
            },
            {
                "value": "2-3days",
                "label": "Within 2–3 days"
            },
            {
                "value": "week",
                "label": "Within a week"
            },
            {
                "value": "month",
                "label": "Within a month"
            },
            {
                "value": "flexible",
                "label": "Flexible / No rush"
            }
        ]
    },
    "budget": {
        "id": "budget",
        "key": "budget",
        "type": "slider",
        "required": false,
        "title": "What is your budget?",
        "subtitle": "Professionals will send quotes based on this",
        "min": 1000,
        "max": 100000,
        "step": 500,
        "format": "₹{value}",
        "defaultValue": 5000
    },
    "description": {
        "id": "description",
        "key": "description",
        "type": "textarea",
        "required": true,
        "title": "Describe your requirement",
        "subtitle": "More detail helps professionals give you accurate quotes",
        "placeholder": "Please describe what you need in detail...",
        "minLength": 20,
        "maxLength": 1000,
        "validation": "Minimum 20 characters required"
    },
    "preferred_professional": {
        "id": "preferred_professional",
        "key": "preferred_professional",
        "type": "single",
        "required": false,
        "title": "What type of professional do you prefer?",
        "options": [
            {
                "value": "individual_ca",
                "label": "Individual CA / Freelancer"
            },
            {
                "value": "firm",
                "label": "CA Firm / Agency"
            },
            {
                "value": "no_preference",
                "label": "No preference"
            }
        ]
    },
    "contact_method": {
        "id": "contact_method",
        "key": "contact_method",
        "type": "single",
        "required": true,
        "title": "How should professionals contact you?",
        "options": [
            {
                "value": "platform_chat",
                "label": "Chat on WorkIndex"
            },
            {
                "value": "phone",
                "label": "Phone call / WhatsApp"
            },
            {
                "value": "email",
                "label": "Email"
            },
            {
                "value": "any",
                "label": "Any method is fine"
            }
        ]
    }
},
 
    expert: [
    {
        "id": "expert_services",
        "key": "expert_services",
        "type": "multi",
        "required": true,
        "title": "What services do you offer?",
        "subtitle": "Select all that apply",
        "useServiceList": true
    },
    {
        "id": "expert_specialization",
        "key": "expert_specialization",
        "type": "single",
        "required": true,
        "title": "What is your primary specialization?",
        "options": [
            {
                "value": "Chartered Accountant",
                "label": "Chartered Accountant (CA)"
            },
            {
                "value": "Cost Accountant",
                "label": "Cost Accountant (CMA)"
            },
            {
                "value": "Company Secretary",
                "label": "Company Secretary (CS)"
            },
            {
                "value": "Tax Consultant",
                "label": "Tax Consultant"
            },
            {
                "value": "GST Consultant",
                "label": "GST Consultant"
            },
            {
                "value": "Bookkeeper",
                "label": "Bookkeeper / Accountant"
            },
            {
                "value": "Photographer",
                "label": "Photographer"
            },
            {
                "value": "Web Developer",
                "label": "Web / App Developer"
            },
            {
                "value": "Other",
                "label": "Other Professional"
            }
        ]
    },
    {
        "id": "expert_experience",
        "key": "expert_experience",
        "type": "single",
        "required": true,
        "title": "How many years of experience do you have?",
        "options": [
            {
                "value": "0-1",
                "label": "Less than 1 year"
            },
            {
                "value": "1-3",
                "label": "1 – 3 years"
            },
            {
                "value": "3-5",
                "label": "3 – 5 years"
            },
            {
                "value": "5-10",
                "label": "5 – 10 years"
            },
            {
                "value": "10+",
                "label": "More than 10 years"
            }
        ]
    },
    {
        "id": "expert_location",
        "key": "expert_location",
        "type": "single",
        "required": true,
        "title": "Where do you prefer to work?",
        "options": [
            {
                "value": "online",
                "label": "Online / Remotely only"
            },
            {
                "value": "local",
                "label": "Local (in-person preferred)"
            },
            {
                "value": "both",
                "label": "Both online and in-person"
            }
        ]
    },
    {
        "id": "expert_city",
        "key": "expert_city",
        "type": "text",
        "required": true,
        "title": "Which city are you based in?",
        "subtitle": "This helps match you with local clients",
        "placeholder": "e.g. Bengaluru, Mumbai, Delhi..."
    },
    {
        "id": "expert_state",
        "key": "expert_state",
        "type": "single",
        "required": true,
        "title": "Which state are you in?",
        "options": [
            {
                "value": "Andhra Pradesh",
                "label": "Andhra Pradesh"
            },
            {
                "value": "Arunachal Pradesh",
                "label": "Arunachal Pradesh"
            },
            {
                "value": "Assam",
                "label": "Assam"
            },
            {
                "value": "Bihar",
                "label": "Bihar"
            },
            {
                "value": "Chandigarh",
                "label": "Chandigarh"
            },
            {
                "value": "Chhattisgarh",
                "label": "Chhattisgarh"
            },
            {
                "value": "Delhi",
                "label": "Delhi"
            },
            {
                "value": "Goa",
                "label": "Goa"
            },
            {
                "value": "Gujarat",
                "label": "Gujarat"
            },
            {
                "value": "Haryana",
                "label": "Haryana"
            },
            {
                "value": "Himachal Pradesh",
                "label": "Himachal Pradesh"
            },
            {
                "value": "Jammu and Kashmir",
                "label": "Jammu and Kashmir"
            },
            {
                "value": "Jharkhand",
                "label": "Jharkhand"
            },
            {
                "value": "Karnataka",
                "label": "Karnataka"
            },
            {
                "value": "Kerala",
                "label": "Kerala"
            },
            {
                "value": "Ladakh",
                "label": "Ladakh"
            },
            {
                "value": "Madhya Pradesh",
                "label": "Madhya Pradesh"
            },
            {
                "value": "Maharashtra",
                "label": "Maharashtra"
            },
            {
                "value": "Manipur",
                "label": "Manipur"
            },
            {
                "value": "Meghalaya",
                "label": "Meghalaya"
            },
            {
                "value": "Mizoram",
                "label": "Mizoram"
            },
            {
                "value": "Nagaland",
                "label": "Nagaland"
            },
            {
                "value": "Odisha",
                "label": "Odisha"
            },
            {
                "value": "Puducherry",
                "label": "Puducherry"
            },
            {
                "value": "Punjab",
                "label": "Punjab"
            },
            {
                "value": "Rajasthan",
                "label": "Rajasthan"
            },
            {
                "value": "Sikkim",
                "label": "Sikkim"
            },
            {
                "value": "Tamil Nadu",
                "label": "Tamil Nadu"
            },
            {
                "value": "Telangana",
                "label": "Telangana"
            },
            {
                "value": "Tripura",
                "label": "Tripura"
            },
            {
                "value": "Uttar Pradesh",
                "label": "Uttar Pradesh"
            },
            {
                "value": "Uttarakhand",
                "label": "Uttarakhand"
            },
            {
                "value": "West Bengal",
                "label": "West Bengal"
            },
            {
                "value": "Other",
                "label": "Other"
            }
        ]
    },
    {
        "id": "expert_pincode",
        "key": "expert_pincode",
        "type": "pincode",
        "required": true,
        "title": "What is your pincode?",
        "subtitle": "Used to match you with nearby clients",
        "placeholder": "Enter 6-digit pincode"
    },
    {
        "id": "expert_bio",
        "key": "expert_bio",
        "type": "textarea",
        "required": true,
        "title": "Tell clients about yourself",
        "subtitle": "Your bio appears on your public profile",
        "placeholder": "e.g. I am a Chartered Accountant with 8 years of experience...",
        "minLength": 50,
        "maxLength": 500,
        "validation": "Minimum 50 characters required"
    }
],
 
  },
 
  // ─── Answer tag formatters (for browse cards) ────────────
  answerTagFormatters: {
    itrTaxpayerType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    itrAnnualIncome: function(v){ return v.replace('above','> ').replace('below','< '); },
    itrIncomeSources: function(v){ return v.replace('above','> ').replace('below','< '); },
    itrFilingType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    gstServiceType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    gstBusinessType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    gstTurnover: function(v){ return v.replace('above','> ').replace('below','< '); },
    accountingBusinessType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    accountingServiceType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    accountingFrequency: function(v){ return v.replace(/-/g,' '); },
    accountingTransactions: function(v){ return v + ' txns/mo'; },
    auditType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    auditOrgType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    auditTurnover: function(v){ return v.replace('above','> ').replace('below','< '); },
    auditDeadline: function(v){ return v.replace(/_/g,' ') + ' audit'; },
    photographyType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    photographyDuration: function(v){ return v.replace(/-/g,' '); },
    devProjectType: function(v){ return v.charAt(0).toUpperCase() + v.slice(1); },
    devPlatform: function(v){ return Array.isArray(v) ? v.join(', ') : v; },
    devTimeline: function(v){ return v.replace(/-/g,' '); }
  },
 
};
 
Object.freeze(WI_SERVICES);
